/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package com.sujithjay.weldj;

public class weld {
  public static void weld_conf_free(SWIGTYPE_p_WeldConf conf) {
    weldJNI.weld_conf_free(SWIGTYPE_p_WeldConf.getCPtr(conf));
  }

  public static String weld_conf_get(SWIGTYPE_p_WeldConf conf, String key) {
    return weldJNI.weld_conf_get(SWIGTYPE_p_WeldConf.getCPtr(conf), key);
  }

  public static SWIGTYPE_p_WeldConf weld_conf_new() {
    long cPtr = weldJNI.weld_conf_new();
    return (cPtr == 0) ? null : new SWIGTYPE_p_WeldConf(cPtr, false);
  }

  public static void weld_conf_set(SWIGTYPE_p_WeldConf conf, String key, String value) {
    weldJNI.weld_conf_set(SWIGTYPE_p_WeldConf.getCPtr(conf), key, value);
  }

  public static void weld_context_free(SWIGTYPE_p_WeldContext context) {
    weldJNI.weld_context_free(SWIGTYPE_p_WeldContext.getCPtr(context));
  }

  public static SWIGTYPE_p_int64_t weld_context_memory_usage(SWIGTYPE_p_WeldContext context) {
    return new SWIGTYPE_p_int64_t(weldJNI.weld_context_memory_usage(SWIGTYPE_p_WeldContext.getCPtr(context)), true);
  }

  public static SWIGTYPE_p_WeldContext weld_context_new(SWIGTYPE_p_WeldConf conf) {
    long cPtr = weldJNI.weld_context_new(SWIGTYPE_p_WeldConf.getCPtr(conf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_WeldContext(cPtr, false);
  }

  public static SWIGTYPE_p_uint64_t weld_error_code(SWIGTYPE_p_WeldError err) {
    return new SWIGTYPE_p_uint64_t(weldJNI.weld_error_code(SWIGTYPE_p_WeldError.getCPtr(err)), true);
  }

  public static void weld_error_free(SWIGTYPE_p_WeldError err) {
    weldJNI.weld_error_free(SWIGTYPE_p_WeldError.getCPtr(err));
  }

  public static String weld_error_message(SWIGTYPE_p_WeldError err) {
    return weldJNI.weld_error_message(SWIGTYPE_p_WeldError.getCPtr(err));
  }

  public static SWIGTYPE_p_WeldError weld_error_new() {
    long cPtr = weldJNI.weld_error_new();
    return (cPtr == 0) ? null : new SWIGTYPE_p_WeldError(cPtr, false);
  }

  public static void weld_load_library(String filename, SWIGTYPE_p_WeldError err) {
    weldJNI.weld_load_library(filename, SWIGTYPE_p_WeldError.getCPtr(err));
  }

  public static SWIGTYPE_p_WeldModule weld_module_compile(String code, SWIGTYPE_p_WeldConf conf, SWIGTYPE_p_WeldError err) {
    long cPtr = weldJNI.weld_module_compile(code, SWIGTYPE_p_WeldConf.getCPtr(conf), SWIGTYPE_p_WeldError.getCPtr(err));
    return (cPtr == 0) ? null : new SWIGTYPE_p_WeldModule(cPtr, false);
  }

  public static void weld_module_free(SWIGTYPE_p_WeldModule module) {
    weldJNI.weld_module_free(SWIGTYPE_p_WeldModule.getCPtr(module));
  }

  public static SWIGTYPE_p_WeldValue weld_module_run(SWIGTYPE_p_WeldModule module, SWIGTYPE_p_WeldContext context, SWIGTYPE_p_WeldValue arg, SWIGTYPE_p_WeldError err) {
    long cPtr = weldJNI.weld_module_run(SWIGTYPE_p_WeldModule.getCPtr(module), SWIGTYPE_p_WeldContext.getCPtr(context), SWIGTYPE_p_WeldValue.getCPtr(arg), SWIGTYPE_p_WeldError.getCPtr(err));
    return (cPtr == 0) ? null : new SWIGTYPE_p_WeldValue(cPtr, false);
  }

  public static void weld_set_log_level(SWIGTYPE_p_uint64_t level) {
    weldJNI.weld_set_log_level(SWIGTYPE_p_uint64_t.getCPtr(level));
  }

  public static SWIGTYPE_p_WeldContext weld_value_context(SWIGTYPE_p_WeldValue value) {
    long cPtr = weldJNI.weld_value_context(SWIGTYPE_p_WeldValue.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_WeldContext(cPtr, false);
  }

  public static SWIGTYPE_p_void weld_value_data(SWIGTYPE_p_WeldValue value) {
    long cPtr = weldJNI.weld_value_data(SWIGTYPE_p_WeldValue.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void weld_value_free(SWIGTYPE_p_WeldValue value) {
    weldJNI.weld_value_free(SWIGTYPE_p_WeldValue.getCPtr(value));
  }

  public static SWIGTYPE_p_WeldValue weld_value_new(SWIGTYPE_p_void data) {
    long cPtr = weldJNI.weld_value_new(SWIGTYPE_p_void.getCPtr(data));
    return (cPtr == 0) ? null : new SWIGTYPE_p_WeldValue(cPtr, false);
  }

  public static SWIGTYPE_p_int64_t weld_value_run(SWIGTYPE_p_WeldValue value) {
    return new SWIGTYPE_p_int64_t(weldJNI.weld_value_run(SWIGTYPE_p_WeldValue.getCPtr(value)), true);
  }

}
