/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package com.sujithjay.weldj;

public class weldJNI {
  public final static native void weld_conf_free(long jarg1);
  public final static native String weld_conf_get(long jarg1, String jarg2);
  public final static native long weld_conf_new();
  public final static native void weld_conf_set(long jarg1, String jarg2, String jarg3);
  public final static native void weld_context_free(long jarg1);
  public final static native long weld_context_memory_usage(long jarg1);
  public final static native long weld_context_new(long jarg1);
  public final static native long weld_error_code(long jarg1);
  public final static native void weld_error_free(long jarg1);
  public final static native String weld_error_message(long jarg1);
  public final static native long weld_error_new();
  public final static native void weld_load_library(String jarg1, long jarg2);
  public final static native long weld_module_compile(String jarg1, long jarg2, long jarg3);
  public final static native void weld_module_free(long jarg1);
  public final static native long weld_module_run(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native void weld_set_log_level(long jarg1);
  public final static native long weld_value_context(long jarg1);
  public final static native long weld_value_data(long jarg1);
  public final static native void weld_value_free(long jarg1);
  public final static native long weld_value_new(long jarg1);
  public final static native long weld_value_run(long jarg1);
}
